version = 0.1

[default.global.parameters]
stack_name = "mastercard-manuals-chatbot"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-east-1"
parameter_overrides = [
  "KnowledgeBaseId=TU_KB_ID_AQUI",
  "ModelArn=arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-5-sonnet-20241022-v2:0",
  "FrontendOrigin=*"
]
