version = 0.1

[default.global.parameters]
stack_name = "mastercard-manuals-chatbot"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-east-1"
parameter_overrides = [
  "KnowledgeBaseId=JOGDDMLYDZ",
  "ModelArn=arn:aws:bedrock:us-east-1::foundation-model/amazon.nova-lite-v1:0",
  "FrontendOrigin=https://main.d3shz2eecr021w.amplifyapp.com"
]
